--TABLES
CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID NUMBER NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    FIRSTNAME VARCHAR(20) NOT NULL,
    LASTNAME VARCHAR(20) NOT NULL,
    IS_MANAGER NUMBER(1),
    CONSTRAINT PK_EMPID PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE RMB_REQUEST
(
    REQUEST_ID NUMBER NOT NULL,
    EMP_ID NUMBER NOT NULL,
    STATUS NUMBER(2) NOT NULL,
    IMAGE VARCHAR(1500),
    MANAGER VARCHAR(20),
    CONSTRAINT PK_REQID PRIMARY KEY (REQUEST_ID)
);

--CONSTRAINTS
ALTER TABLE RMB_REQUEST ADD CONSTRAINT FK_EMPID
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
    ON DELETE CASCADE;

--SEQUENCES

CREATE SEQUENCE SQ_EMPLOYEE_PK
START WITH 1000
INCREMENT BY 1;
/

CREATE SEQUENCE SQ_RMB_REQUEST_PK
START WITH 1
INCREMENT BY 1;
/

--TRIGGERS

CREATE OR REPLACE TRIGGER TR_INSERT_EMPLOYEE
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
  SELECT SQ_EMPLOYEE_PK.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TR_INSERT_RMB_REQUEST
BEFORE INSERT ON RMB_REQUEST
FOR EACH ROW
BEGIN
  SELECT SQ_RMB_REQUEST_PK.NEXTVAL INTO :NEW.REQUEST_ID FROM DUAL;
END;
/

--INSERT INTO EMPLOYEE(USERNAME, PASSWORD, FIRSTNAME, LASTNAME, IS_MANAGER) VALUES('artorias', 'abyss', 'Knight', 'Artorias', 0);

--INSERT INTO EMPLOYEE(USERNAME, PASSWORD, FIRSTNAME, LASTNAME, IS_MANAGER) VALUES('25', '0', 'Tac', 'Nuke', 1);

--commit;    
    
    