
package com.revature.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BradburyException", targetNamespace = "http://service.revature.com/")
public class BradburyException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BradburyException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BradburyException_Exception(String message, BradburyException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BradburyException_Exception(String message, BradburyException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.revature.service.BradburyException
     */
    public BradburyException getFaultInfo() {
        return faultInfo;
    }

}
