
package com.revature.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LibraryImplService", targetNamespace = "http://service.revature.com/", wsdlLocation = "http://localhost:8084/SoapServiceDemo/Library?wsdl")
public class LibraryImplService
    extends Service
{

    private final static URL LIBRARYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LIBRARYIMPLSERVICE_EXCEPTION;
    private final static QName LIBRARYIMPLSERVICE_QNAME = new QName("http://service.revature.com/", "LibraryImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/SoapServiceDemo/Library?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIBRARYIMPLSERVICE_WSDL_LOCATION = url;
        LIBRARYIMPLSERVICE_EXCEPTION = e;
    }

    public LibraryImplService() {
        super(__getWsdlLocation(), LIBRARYIMPLSERVICE_QNAME);
    }

    public LibraryImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIBRARYIMPLSERVICE_QNAME, features);
    }

    public LibraryImplService(URL wsdlLocation) {
        super(wsdlLocation, LIBRARYIMPLSERVICE_QNAME);
    }

    public LibraryImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIBRARYIMPLSERVICE_QNAME, features);
    }

    public LibraryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibraryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Library
     */
    @WebEndpoint(name = "LibraryImplPort")
    public Library getLibraryImplPort() {
        return super.getPort(new QName("http://service.revature.com/", "LibraryImplPort"), Library.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Library
     */
    @WebEndpoint(name = "LibraryImplPort")
    public Library getLibraryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.revature.com/", "LibraryImplPort"), Library.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIBRARYIMPLSERVICE_EXCEPTION!= null) {
            throw LIBRARYIMPLSERVICE_EXCEPTION;
        }
        return LIBRARYIMPLSERVICE_WSDL_LOCATION;
    }

}
