
package com.revature.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Library", targetNamespace = "http://service.revature.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Library {


    /**
     * 
     * @return
     *     returns java.util.List<com.revature.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://service.revature.com/", className = "com.revature.service.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://service.revature.com/", className = "com.revature.service.GetAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws BradburyException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBook", targetNamespace = "http://service.revature.com/", className = "com.revature.service.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://service.revature.com/", className = "com.revature.service.AddBookResponse")
    public String addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0)
        throws BradburyException_Exception
    ;

}
