server:
  port: 8084
#security: 
#  basic:
#    enabled: false
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://35.183.1.239:8761/eureka/

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        hbm2ddl.auto: create
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=Oracle
