CREATE TABLE EMPLOYEE2 (
EMPLOYEE_ID INTEGER PRIMARY KEY, 
EMP_FIRSTNAME VARCHAR2(100), 
EMP_LASTNAME VARCHAR2(100), 
DEPARTMENT_ID INTEGER, 
SALARY INTEGER, 
EMP_EMAIL VARCHAR2(100));

CREATE TABLE DEPARTMENT2 (
DEPARTMENT_ID INTEGER PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(100)
);

ALTER TABLE EMPLOYEE2
ADD CONSTRAINT FK_EMPLOYEE2_DEPARTMENT2
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT2(DEPARTMENT_ID)
ON DELETE SET NULL;

CREATE SEQUENCE SQ_EMPLOYEE2_PK
START WITH 5
INCREMENT BY 2;
/

CREATE SEQUENCE SQ_DEPARTMENT2_PK
START WITH 5
INCREMENT BY 3;
/

CREATE OR REPLACE TRIGGER TR_INSERT_EMPLOYEE2
BEFORE INSERT ON EMPLOYEE2
FOR EACH ROW
BEGIN
  SELECT SQ_EMPLOYEE2_PK.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TR_INSERT_DEPARTMENT2
BEFORE INSERT ON DEPARTMENT2
FOR EACH ROW
BEGIN
  SELECT SQ_DEPARTMENT2_PK.NEXTVAL INTO :NEW.DEPARTMENT_ID FROM DUAL;
END;
/

INSERT INTO DEPARTMENT2 (DEPARTMENT_NAME) VALUES ('Accounting');
INSERT INTO DEPARTMENT2 (DEPARTMENT_NAME) VALUES ('Infirmary');
INSERT INTO DEPARTMENT2 (DEPARTMENT_NAME) VALUES ('Recreation');

INSERT INTO EMPLOYEE2 (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('FNAME1', 'LNAME1', 65, 5000, 'FNAME1@REVATURE.COM');
INSERT INTO EMPLOYEE2 (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('FNAME2', 'LNAME2', 65, 6000, 'FNAME2@REVATURE.COM');
INSERT INTO EMPLOYEE2 (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('FNAME3', 'LNAME3', 68, 7000, 'FNAME3@REVATURE.COM');
INSERT INTO EMPLOYEE2 (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('FNAME4', 'LNAME4', 68, 8000, 'FNAME4@REVATURE.COM');
INSERT INTO EMPLOYEE2 (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('FNAME5', 'LNAME5', 71, 9000, 'FNAME5@REVATURE.COM');
INSERT INTO EMPLOYEE2 (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('FNAME6', 'LNAME6', 71, 10000, 'FNAME6@REVATURE.COM');

CREATE OR REPLACE PROCEDURE SP_GIVE_RAISE
(
DEPARTMENT2_ID IN DEPARTMENT2.DEPARTMENT_ID%TYPE,
AVG_SALARY OUT INTEGER
) AS
BEGIN

    UPDATE EMPLOYEE2 SET SALARY = (SALARY + (SALARY / 10)) WHERE DEPARTMENT_ID=DEPARTMENT2_ID;
    SELECT AVG(SALARY) INTO AVG_SALARY FROM EMPLOYEE2 WHERE DEPARTMENT_ID=DEPARTMENT2_ID;
    
END;
/

select * from EMPLOYEE2;
SELECT * FROM DEPARTMENT2;
SELECT AVG(SALARY) FROM EMPLOYEE2;