CREATE TABLE MEMBER (
    NO NUMBER(10) PRIMARY KEY,                          -- USER NUMBER
    ID VARCHAR2(50) NOT NULL UNIQUE,                    -- LOGIN ID
    PWD VARCHAR2(50) NOT NULL CHECK (LENGTH(PWD)>=4),  
    EMAIL VARCHAR2(100) NOT NULL UNIQUE, -- LOGIN PASSWORD
    LV VARCHAR(2) NOT NULL                              -- 0: MANAGER / 1: EMPLOYEE
);
 commit;
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'EMP1', '0001', 'emp001@gmail.com', '1'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'EMP2', '0002', 'emp002@gmail.com', '1'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'EMP3', '0003', 'emp003@gmail.com', '1'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'EMP4', '0004', 'emp004@gmail.com', '1'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'EMP5', '0005', 'emp005@gmail.com', '1'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'EMP6', '0006', 'emp006@gmail.com', '1'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'EMP7', '0007', 'emp007@gmail.com', '1'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'EMP8', '0008', 'emp008@gmail.com', '1'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'EMP9', '0009', 'emp009@gmail.com', '1'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'MANAGER1', '0001', 'mng001@gmail.com', '0'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'MANAGER2', '0002', 'mng002@gmail.com', '0'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'MANAGER3', '0003', 'mng003@gmail.com', '0'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'MANAGER4', '0004', 'mng004@gmail.com', '0'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'MANAGER5', '0005', 'mng005@gmail.com', '0'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'MANAGER6', '0006', 'mng006@gmail.com', '0'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'MANAGER7', '0007', 'mng007@gmail.com', '0'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'MANAGER8', '0008', 'mng008@gmail.com', '0'); 
INSERT INTO MEMBER(NO, ID, PWD, EMAIL, LV) VALUES(MEMBER_SEQ.NEXTVAL, 'MANAGER9', '0009', 'mng009@gmail.com', '0'); 
commit;

-- pending doesn't have value
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 1, SYSDATE, 150, 'BUSINESS TRIP', 41, null);     
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 2, SYSDATE, 150, 'BUSINESS TRIP', 41, 56);
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 3, SYSDATE, 150, 'OFFICE SUPPLY PURCHASE', 41, 52);
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 2, SYSDATE, 150, 'BUSINESS TRIP', 41, 53);
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 2, SYSDATE, 150, 'OFFICE SUPPLY PURCHASE', 42, 52);
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 2, SYSDATE, 150, 'BUSINESS TRIP', 41, 53);
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 3, SYSDATE, 150, 'OFFICE SUPPLY PURCHASE', 41, 52);
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 2, SYSDATE, 150, 'OFFICE SUPPLY PURCHASE', 41, 53);
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 3, SYSDATE, 150, 'RELOCATION', 41, 52);
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 3, SYSDATE, 150, 'RELOCATION', 42, 52);
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 2, SYSDATE, 150, 'BUSINESS TRIP', 47, 55);
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 3, SYSDATE, 150, 'OFFICE SUPPLY PURCHASE', 48, 56);
INSERT INTO REQUEST( NO, STATUS, DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, MANAGER_NO) 
VALUES (REQUEST_SEQ.NEXTVAL, 2, SYSDATE, 150, 'BUSINESS TRIP', 41, 58);

commit;

INSERT INTO REQUEST (NO, AMOUNT, PURPOSE, EMPLOYEE_NO) VALUES (); 
CREATE TABLE REQUEST (
    NO NUMBER(10) PRIMARY KEY,                      -- REQUEST NUMBER
    STATUS NUMBER(1) DEFAULT 1 NOT NULL CHECK (STATUS<4),            -- 1:PENDING 2:APPROVED 3:DENIED
    DAY DATE DEFAULT SYSDATE NOT NULL,                              -- DATE REQUEST SUBMITTED.
    AMOUNT NUMBER(10) NOT NULL CHECK(AMOUNT >0),    -- MONEY REQUESTED            
    PURPOSE VARCHAR2(100),
    EMPLOYEE_NO NUMBER(10) NOT NULL,                -- WHO SUBMIT
    MANAGER_NO NUMBER(10),                          -- WHO RESOLVED
    
    CONSTRAINT REQUEST_FK FOREIGN KEY (EMPLOYEE_NO) REFERENCES MEMBER(NO)
    --CONSTRAINT REQUEST_FK FOREIGN KEY (MANAGER_NO) REFERENCES MEMBER(NO)
);

DROP TABLE REQUEST;
DROP TABLE IMG;
CREATE TABLE IMG (
    NO NUMBER(10) PRIMARY KEY,
    REQUEST_NO NUMBER(10) NOT NULL,
    FILENAME VARCHAR2(100) NOT NULL,   -- filename + requestno
    CONSTRAINT IMG_FK FOREIGN KEY (REQUEST_NO) REFERENCES REQUEST(NO)
);


CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1;
 
CREATE SEQUENCE REQUEST_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE IMG_SEQ
START WITH 1
INCREMENT BY 1;
 

SELECT count(*) as cnt
FROM MEMBER M  JOIN REQUEST R
ON M.NO = R.EMPLOYEE_NO
WHERE R.EMPLOYEE_NO = 62;

-- Status, title (purpose+amount) , date, request_primary no per a employee
-- by page num : 1 (1~10) , 2 (11~20), 3(21~30)  (X*10-9)~ X*10
SELECT RW, R_NO, STATUS, DAY, AMOUNT, PURPOSE
FROM ( SELECT ROWNUM AS RW, R.NO AS R_NO, R.STATUS AS STATUS, R.DAY AS DAY, R.AMOUNT AS AMOUNT, R.PURPOSE AS PURPOSE
        FROM MEMBER M  JOIN REQUEST R
        ON M.NO = R.EMPLOYEE_NO
        WHERE R.EMPLOYEE_NO = 41)
WHERE RW BETWEEN 11 AND 20 ;


SELECT CASE WHEN COUNT(R.STATUS) > 0 THEN COUNT(R.STATUS) 
ELSE 0 END AS CNT, R.STATUS AS STATUS 
--COUNT(R.STATUS) AS CNT, R.STATUS AS STATUS
FROM MEMBER M LEFT JOIN REQUEST R
ON M.NO = R.EMPLOYEE_NO
WHERE M.NO = 61
GROUP BY R.STATUS;

INSERT INTO REQUEST (NO, AMOUNT, PURPOSE, EMPLOYEE_NO) VALUES 
(REQUEST_SEQ.NEXTVAL, 133, 'BUSINESS TRIP', 42);

INSERT INTO IMG (NO, REQUEST_NO, FILENAME) VALUES (42, 40, 'receipt_orange.jpg');

SELECT NO, STATUS, TO_CHAR(DAY, 'YYYY-MM-DD') AS DAY, AMOUNT, PURPOSE, EMPLOYEE_NO, NVL(MANAGER_NO, 0) AS MANAGER_NO FROM REQUEST WHERE NO = 42;
SELECT NO, REQUEST_NO, FILENAME FROM IMG WHERE REQUEST_NO = 30;
COMMIT;

SELECT C.THEROW AS THEROW, C.EMPLOYEE_ID AS EMPLOYEE_ID, C.NO AS NO, 
        C.STATUS AS STATUS, C.DAY AS DAY, C.AMOUNT AS AMOUNT, C.PURPOSE AS PURPOSE, 
       C.EMPLOYEE_NO AS EMPLOYEE_NO,  C.MANAGER_NO AS MANAGER_NO
FROM (SELECT ROWNUM AS THEROW, A.EMPLOYEE_ID AS EMPLOYEE_ID,
        A.NO AS NO, A.STATUS AS STATUS,
        A.DAY AS DAY, A.PURPOSE AS PURPOSE, A.AMOUNT AS AMOUNT,
        A.EMPLOYEE_NO AS EMPLOYEE_NO, A.MANAGER_NO AS MANAGER_NO
        FROM (SELECT M.ID AS EMPLOYEE_ID, R.NO AS NO, R.STATUS AS STATUS, 
                TO_CHAR(R.DAY, 'YYYY-MM-DD') AS DAY, R.AMOUNT AS AMOUNT,
                R.PURPOSE AS PURPOSE, R.EMPLOYEE_NO AS EMPLOYEE_NO, NVL(R.MANAGER_NO, 0) AS MANAGER_NO
                FROM REQUEST R, MEMBER M
                WHERE M.NO = R.EMPLOYEE_NO
                ORDER BY R.NO DESC) A) C
WHERE C.THEROW BETWEEN (2*10-9) AND (2*10);  -- 2*10-9 ~ 2*10



SELECT R.NO AS NO, R.STATUS AS STATUS, TO_CHAR(R.DAY, 'YYYY-MM-DD') AS DAY,
R.PURPOSE AS PURPOSE, R.AMOUNT AS AMOUNT,
R.EMPLOYEE_NO AS EMPLOYEE_NO, 
NVL(R.MANAGER_NO,0) AS MANAGER_NO, 
M.ID AS EMPLOYEE_ID
--NVL((SELECT MG.ID FROM MEMBER MG WHERE MG.NO=R.MANAGER_NO),'0') AS MANAGER_ID
        FROM REQUEST R, MEMBER M
        WHERE M.NO = R.EMPLOYEE_NO
        AND R.NO = 103;

SELECT R.NO AS NO, R.STATUS AS STATUS, TO_CHAR(R.DAY, 'YYYY-MM-DD') AS DAY,
R.PURPOSE AS PURPOSE, R.AMOUNT AS AMOUNT,
R.EMPLOYEE_NO AS EMPLOYEE_NO, 
NVL(R.MANAGER_NO,0) AS MANAGER_NO,
(SELECT ME.ID FROM MEMBER ME WHERE R.EMPLOYEE_NO = ME.NO) AS EMPLOYEE_ID,
NVL((SELECT MG.ID FROM MEMBER MG WHERE R.MANAGER_NO = MG.NO),'0') AS MANAGER_ID
FROM REQUEST R
WHERE R.NO = 40;

TRUNCATE TABLE IMG;
TRUNCATE TABLE REQUEST;
TRUNCATE TABLE MEMBER;

UPDATE SET REQUEST 
ON STATUS = 10,
MANAGER_NO = 10
WHERE REQUEST_NO = 10;


--Employee ID	Total Request Count	/Total Amount
SELECT C.THEROW AS THEROW, C.EMPLOYEE_NO AS EMPLOYEE_NO, C.SUM AS TOTAL_AMOUNT, C.CNT AS CNT,
(SELECT ID FROM MEMBER WHERE NO=C.EMPLOYEE_NO) AS EMPLOYEE_ID
FROM (SELECT ROWNUM AS THEROW, A.EMPLOYEE_NO AS EMPLOYEE_NO, A.SUM AS SUM, A.CNT AS CNT
FROM (SELECT EMPLOYEE_NO, SUM(AMOUNT) AS SUM, COUNT(*) AS CNT
FROM REQUEST 
GROUP BY EMPLOYEE_NO
ORDER BY COUNT(*) DESC) A) C
WHERE C.THEROW BETWEEN (1*10-9) AND (1*10);



SELECT C.THEROW AS THEROW, C.R_NO AS R_NO, C.STATUS AS STATUS, 
C.DAY AS DAY, C.AMOUNT AS AMOUNT, C.PURPOSE AS PURPOSE
FROM ( SELECT ROWNUM AS THEROW, A.R_NO AS R_NO, A.STATUS AS STATUS, 
              A.DAY AS DAY, A.AMOUNT AS AMOUNT, A.PURPOSE AS PURPOSE
        FROM  (SELECT R.NO AS R_NO, R.STATUS AS STATUS, 
               TO_CHAR(R.DAY, 'YYYY-MM-DD') AS DAY, 
                R.AMOUNT AS AMOUNT, R.PURPOSE AS PURPOSE 
                FROM MEMBER M  JOIN REQUEST R  
                ON M.NO = R.EMPLOYEE_NO  
        WHERE R.EMPLOYEE_NO = 102 ORDER BY R.NO DESC)A)C
WHERE C.THEROW  BETWEEN (1*10-9) AND (1*10);

SELECT * FROM MEMBER;

UPDATE SET REQUEST 
ON STATUS = 10,
MANAGER_NO = 10
WHERE REQUEST_NO = 10;

-- email 
SELECT count(*)
FROM MEMBER
WHERE no != 103
and EMAIL= 'emp3@gmail.com';


UPDATE MEMBER SET
PWD = '00002', 
EMAIL = 'employee02@gmail.com' 
WHERE NO = 103;