CREATE TABLE BANK_USERS(
USERID INT,
USERNAME VARCHAR(255),
USERPASS VARCHAR(255),
PRIMARY KEY (USERID)
);

CREATE SEQUENCE USER_SEQUENCE
MINVALUE 0
START WITH 1000
INCREMENT BY 1;

CREATE TABLE BANK_ACCOUNT(
ACCOUNTID INT,
ACCOUNTNAME VARCHAR(255),
AMOUNT FLOAT,
PRIMARY KEY (ACCOUNTID)
);

DROP SEQUENCE ACCOUNT_SEQUENCE;

CREATE SEQUENCE ACCOUNT_SEQUENCE
MINVALUE 0
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE ACCOUNTLINK_SEQUENCE
MINVALUE 0
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE USERACCOUNT_SEQUENCE
MINVALUE 0
START WITH 1000
INCREMENT BY 1;

CREATE SEQUENCE SUPERUSER_SEQUENCE
MINVALUE 0
START WITH 1000
INCREMENT BY 1;

--This table links together the users and accounts
--Multiple users can access a single account
CREATE TABLE BANK_USERACCOUNTS(
USERACCOUNTID INT,
ACCOUNTID INT,
USERID INT,
PRIMARY KEY (USERACCOUNTID)
);

ALTER TABLE BANK_USERACCOUNTS ADD CONSTRAINT FK_ACCOUNTID
    FOREIGN KEY (ACCOUNTID) REFERENCES BANK_ACCOUNT(ACCOUNTID);
    
ALTER TABLE BANK_USERACCOUNTS ADD CONSTRAINT FK_USERID
    FOREIGN KEY (USERID) REFERENCES BANK_USERS(USERID);
    
--Super user modification is ONLY USED HERE NOT IN THE JAVA PROGRAM
CREATE TABLE BANK_SUPERUSERS(
SUPERUSERID INT,
USERID INT,
PRIMARY KEY (SUPERUSERID)
);   

ALTER TABLE BANK_SUPERUSERS ADD CONSTRAINT FK_SUSERID
    FOREIGN KEY (USERID) REFERENCES BANK_USERS(USERID);
    
INSERT INTO BANK_USERS VALUES(1,'RickyBobby','talladega');
INSERT INTO BANK_SUPERUSERS VALUES(1, 1); --1 is RickyBobby, the obvious choice for a superuser
    
SELECT * FROM BANK_ACCOUNT 
INNER JOIN BANK_USERACCOUNTS 
ON BANK_ACCOUNT.ACCOUNTID=BANK_USERACCOUNTS.ACCOUNTID 
WHERE BANK_USERACCOUNTS.USERID = 1000;

SELECT USER_SEQUENCE.CURRVAL FROM DUAL;

SELECT * FROM BANK_USERS WHERE USERNAME='joshBrandl';

SELECT * FROM BANK_USERS WHERE USERPASS IS NOT NULL;

--DELETE FROM BANK_USERACCOUNTS WHERE ACCOUNTID=?"
CREATE OR REPLACE PROCEDURE DELETE_BANK_ACCOUNT
(ACCOUNT_ID INT)
IS
BEGIN
    DELETE FROM BANK_USERACCOUNTS WHERE ACCOUNTID=ACCOUNT_ID;
    DELETE FROM BANK_ACCOUNT WHERE ACCOUNTID=ACCOUNT_ID;
    
END;
/