ALTER SESSION SET CURRENT_SCHEMA = CHINOOK;

-- 2.1 SELECT

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE LASTNAME = 'King';

SELECT *
FROM EMPLOYEE
WHERE FIRSTNAME = 'Andrew'
      AND   REPORTSTO IS NULL;
      
-- 2.2 ORDER BY

SELECT * FROM ALBUM
ORDER BY TITLE DESC;

SELECT * FROM CUSTOMER
ORDER BY CITY ASC;