DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INTEGER CONSTRAINT PK_DEPARTMENT_ID PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(20));

CREATE TABLE EMPLOYEE2 (
    EMPLOYEE_ID INTEGER CONSTRAINT PK_EMPLOYEE_ID PRIMARY KEY, 
    EMP_FIRSTNAME VARCHAR2(20),
    EMP_LASTNAME VARCHAR2(20),
    DEPARTMENT_ID INTEGER REFERENCES DEPARTMENT(DEPARTMENT_ID),
    SALARY NUMBER(8,2),
    EMP_EMAIL VARCHAR(20));
    
CREATE SEQUENCE EMPLOYEE_ID_SEQUENCE
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 10;
  
  CREATE SEQUENCE DEPARTMENT_ID_SEQUENCE
  MINVALUE 10
  START WITH 10
  INCREMENT BY 5
  CACHE 5;
  
COMMIT;

CREATE OR REPLACE TRIGGER TR_INSERT_EMPLOYEE_ID
BEFORE INSERT ON EMPLOYEE2
FOR EACH ROW
BEGIN 
SELECT EMPLOYEE_ID_SEQUENCE.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;
/

COMMIT;
CREATE OR REPLACE TRIGGER TR_INSERT_DEPARTMENT_ID
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN 
SELECT DEPARTMENT_ID_SEQUENCE.NEXTVAL INTO :NEW.DEPARTMENT_ID FROM DUAL;
END;
/

COMMIT;

INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ('Sales');
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ('Human Resources');
INSERT INTO DEPARTMENT (DEPARTMENT_NAME) VALUES ('Admin');

SELECT * FROM EMPLOYEE2;

INSERT INTO EMPLOYEE2 (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID,SALARY, EMP_EMAIL) 
VALUES ('Jaden', 'Park', 10,15000, 'jpkhbj@gmail.com');
INSERT INTO EMPLOYEE2 (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID,SALARY, EMP_EMAIL) 
VALUES ('Keala', 'Best', 15,50000, 'kbest@gmail.com');
INSERT INTO EMPLOYEE2 (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID,SALARY, EMP_EMAIL) 
VALUES ('Samuel', 'fisher', 10,15000, 'jpkhbj@gmail.com');
INSERT INTO EMPLOYEE2 (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID,SALARY, EMP_EMAIL) 
VALUES ('Jaden', 'Park', 10,15000, 'jpkhbj@gmail.com');
INSERT INTO EMPLOYEE2 (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID,SALARY, EMP_EMAIL) 
VALUES ('Jaden', 'Park', 10,15000, 'jpkhbj@gmail.com');
INSERT INTO EMPLOYEE2 (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID,SALARY, EMP_EMAIL) 
VALUES ('Jaden', 'Park', 10,15000, 'jpkhbj@gmail.com');
