CREATE OR REPLACE PROCEDURE GET_ALL_ALBUMS (
    C OUT SYS_REFCURSOR
)
    AS
BEGIN
    OPEN C FOR SELECT ALBUMID,TITLE FROM ALBUM;
END;
/
DECLARE
    S SYS_REFCURSOR;
    ALBUM_ID ALBUM.ALBUMID%TYPE;
    ALBUMNAME ALBUM.TITLE%TYPE;
BEGIN
    GET_ALL_ALBUMS(S);
    LOOP
        FETCH S INTO ALBUM_ID,ALBUMNAME;
        EXIT WHEN S%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(ALBUM_ID
        || ' is current id '
        || ALBUMNAME
        || ' is current name');
    END LOOP;
    CLOSE S;
END;
/