--JAMES WHITTEN
--EXPENSE REIMBURSEMENT SYSTEM

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID NUMBER NOT NULL,
    EMPLOYEE_FNAME VARCHAR2(60) NOT NULL,
    EMPLOYEE_LNAME VARCHAR2(60) NOT NULL,
    EMPLOYEE_EMAIL VARCHAR2(60),
    EMPLOYEE_PASSWORD VARCHAR2(60),
	EMPLOYEE_ACCOUNT VARCHAR2(60),
	IS_MANAGER NUMBER NOT NULL,
    CONSTRAINT PK_Employee PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE MANAGER
(
    EMPLOYEE_ID NUMBER NOT NULL,
    MANAGER_ID NUMBER NOT NULL,
	REQUEST_ID NUMBER NOT NULL,
    CONSTRAINT PK_Manager PRIMARY KEY (EMPLOYEE_ID, MANAGER_ID, REQUEST_ID)
);

CREATE TABLE FILES
(
    FILE_ID NUMBER NOT NULL,
    FILENAME VARCHAR2(120) NOT NULL,
    REQUEST_ID NUMBER NOT NULL,
	FILE_URL VARCHAR(160) NOT NULL,
    CONSTRAINT PK_File PRIMARY KEY (FILE_ID)
);

CREATE TABLE LOOKUP
(
    LOOKUP_ID NUMBER NOT NULL,
    KEYWORD VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_Lookup PRIMARY KEY (LOOKUP_ID)
);

CREATE TABLE REQUEST
(
    REQUEST_ID NUMBER NOT NULL,
    EMPLOYEE_ID NUMBER NOT NULL,
    TYPE_ID NUMBER NOT NULL,
    STATUS_ID NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(160),
    AMOUNT NUMBER NOT NULL,
	STATUS_DATE DATE NOT NULL,
	SUBMIT_DATE DATE NOT NULL,
	MANAGER_ID NUMBER NOT NULL,
    CONSTRAINT PK_Request PRIMARY KEY (REQUEST_ID)
);

CREATE TABLE NOTES
(
    NOTE_ID NUMBER NOT NULL,
    REQUEST_ID NUMBER NOT NULL,
    NOTE_DATE DATE NOT NULL,
    NOTE_MESSAGE VARCHAR2(160),
	NOTETAKER_ID NUMBER NOT NULL,
    CONSTRAINT PK_Notes PRIMARY KEY (NOTE_ID)
);


ALTER TABLE REQUEST ADD CONSTRAINT FK_EMP_REQUESTED
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID) ;

ALTER TABLE REQUEST ADD CONSTRAINT FK_REQ_TYPE
FOREIGN KEY (TYPE_ID) REFERENCES LOOKUP (LOOKUP_ID) ;

ALTER TABLE REQUEST ADD CONSTRAINT FK_STATUS_TYPE
FOREIGN KEY (STATUS_ID) REFERENCES LOOKUP (LOOKUP_ID) ;

ALTER TABLE REQUEST ADD CONSTRAINT FK_RES_MANAGER
FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID) ;

ALTER TABLE FILES ADD CONSTRAINT FK_FILE_REQUEST
FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST (REQUEST_ID) ;

ALTER TABLE NOTES ADD CONSTRAINT FK_NOTE_REQUEST
FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST (REQUEST_ID) ;

ALTER TABLE NOTES ADD CONSTRAINT FK_NOTE_NOTETAKER
FOREIGN KEY (NOTETAKER_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID) ;

ALTER TABLE EMPLOYEE ADD CONSTRAINT E_ACCOUNTNAME UNIQUE (EMPLOYEE_ACCOUNT);

CREATE SEQUENCE EMP_NUM_SEQ
START WITH 1001;

CREATE SEQUENCE FILE_NUM_SEQ
START WITH 1001;

CREATE SEQUENCE LOOKUP_NUM_SEQ
START WITH 1001;

CREATE SEQUENCE NOTE_NUM_SEQ
START WITH 1001;

CREATE SEQUENCE REQ_NUM_SEQ
START WITH 1001;

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (1, 'Submitted');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (2, 'Pending');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (3, 'More Info Required');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (4, 'Cancelled');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (5, 'Declined');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (6, 'Approved');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (11, 'Business');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (12, 'Travel');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (13, 'Housing');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (14, 'Education');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (15, 'Hiring');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (16, 'Inventory');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (17, 'Food');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (18, 'Personal');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (19, 'Insurance');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (20, 'Entertainment');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (21, 'Misc.');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (100, 'EMPLOYEE');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (101, 'MANAGER');

INSERT INTO LOOKUP (LOOKUP_ID, KEYWORD)
VALUES (102, 'SENIOR MANAGER');