CREATE OR REPLACE PROCEDURE SP_FEED_BEAR (
    N_BEARID IN NUMBER,N_BEEHIVEID IN NUMBER,N_HONEYAMT IN NUMBER
) AS
    N_PREV_HONEY_WEIGHT NUMBER;
    N_PREV_BEAR_WEIGHT NUMBER;
    N_NEW_BEEHIVE NUMBER;
    N_NEW_BEAR NUMBER;
BEGIN
    SELECT WEIGHT INTO
        N_PREV_BEAR_WEIGHT
    FROM BEAR
    WHERE BEAR_ID = N_BEARID;
    SELECT WEIGHT INTO
        N_PREV_HONEY_WEIGHT
    FROM BEEHIVE
    WHERE BEEHIVE_ID = N_BEEHIVEID;
    IF
        N_HONEYAMT > N_PREV_HONEY_WEIGHT
    THEN
        DBMS_OUTPUT.PUT_LINE('Not enough honey in the beehive.');
    ELSE
        N_NEW_BEEHIVE := N_PREV_HONEY_WEIGHT - N_HONEYAMT;
        N_NEW_BEAR := N_PREV_BEAR_WEIGHT + N_HONEYAMT;
        UPDATE BEAR
            SET
                BEAR_WEIGHT = N_NEW_BEAR
        WHERE BEAR_ID = N_BEARID;
        UPDATE BEEHIVE
            SET
                BEEHIVE_WEIGHT = N_NEW_BEEHIVE
        WHERE BEEHIVE_ID = N_BEEHIVEID;
    END IF;
END;