--Create Functions using Chinook DB!
--
--1.Find the average number of songs per album for a given artist(artist Id is ok)
--ex. CREATE FUNCTION AVGSONG....
CREATE OR REPLACE FUNCTION AVG_SONGS_PER_ALBUM (
    N_ARTISTID IN NUMBER
) RETURN NUMBER AS
    N_ALBUM_COUNT   NUMBER(8,2);
    N_SONG_COUNT    NUMBER(8,2);
BEGIN
    SELECT COUNT(ALBUMID) INTO
        N_ALBUM_COUNT
    FROM ALBUM
    WHERE ARTISTID = N_ARTISTID;
    
    SELECT COUNT(TRACKID) INTO
        N_SONG_COUNT
    FROM ARTIST
    INNER JOIN ALBUM ON ARTIST.ARTISTID = ALBUM.ARTISTID
    INNER JOIN TRACK ON ALBUM.ALBUMID = TRACK.ALBUMID
    WHERE ARTIST.ARTISTID = N_ARTISTID;
    RETURN N_SONG_COUNT / N_ALBUM_COUNT;
END;
/
SELECT AVG_SONGS_PER_ALBUM(12) FROM DUAL;
/
--
--TO CALL FUNCTION:
--BEGIN
--AVGSONG(PARAMETER1);
--END;
--
--2.Find the longest track of an album for a given album id.
CREATE OR REPLACE FUNCTION MAX_LEN_TRACK (
    N_ALBUMID IN NUMBER
) RETURN VARCHAR2 AS
    VC_TRACK_NAME   VARCHAR2(20);
BEGIN
    SELECT TRACK.NAME INTO
        VC_TRACK_NAME
    FROM TRACK
    WHERE ALBUMID = N_ALBUMID
          AND   MILLISECONDS = (
        SELECT MAX(MILLISECONDS)
        FROM TRACK
        WHERE ALBUMID = N_ALBUMID
    );
    RETURN VC_TRACK_NAME;
END;
/
SELECT MAX_LEN_TRACK(5) FROM DUAL;