CREATE TABLE EMPLOYEE (
    EMP_ID INTEGER CONSTRAINT PK_EMPLOYEE_ID PRIMARY KEY, 
    FIRSTNAME VARCHAR2(20) CONSTRAINT EMP_FIRSTNAME_NN NOT NULL,
    LASTNAME VARCHAR2(20) CONSTRAINT EMP_LASTNAME_NN NOT NULL,
    EMAIL VARCHAR2(30) CONSTRAINT EMP_EMAIL_NN NOT NULL,
    EMP_PASSWORD VARCHAR2(20) CONSTRAINT EMP_PASSWORD_NN NOT NULL,
    ADDRESS VARCHAR2(20),
    CITY VARCHAR2(20),
    STATE VARCHAR2(20),
    ROUTING_NUMBER INTEGER CONSTRAINT ROUTING_NUMBER_NN NOT NULL,
    ACCOUNT_NUMBER INTEGER CONSTRAINT ACCOUNT_NUMBER_NN NOT NULL);
    
CREATE TABLE MANAGER (
    MAN_ID INTEGER CONSTRAINT PK_MANAGER_ID PRIMARY KEY, 
    FIRSTNAME VARCHAR2(20) CONSTRAINT MAN_FIRSTNAME_NN NOT NULL,
    LASTNAME VARCHAR2(20) CONSTRAINT MAN_LASTNAME_NN NOT NULL,
    EMAIL VARCHAR2(30) CONSTRAINT MAN_EMAIL_NN NOT NULL,
    EMP_PASSWORD VARCHAR2(20) CONSTRAINT EMP_PASSWORD_NN NOT NULL,
    ADDRESS VARCHAR2(20),
    CITY VARCHAR2(20),
    STATE VARCHAR2(20)
    );
    
CREATE TABLE REQUEST (
    REQUEST_ID INTEGER CONSTRAINT PK_REQUEST_ID PRIMARY KEY,
    EMP_ID INTEGER CONSTRAINT FK_EMPLOYEE_ID REFERENCES EMPLOYEE(EMP_ID) ON DELETE SET NULL,
    MAN_ID INTEGER CONSTRAINT FK_MANAGER_ID REFERENCES MANAGER(MAN_ID) ON DELETE SET NULL,
    AMOUNT NUMBER CONSTRAINT AMOUNT_NN NOT NULL,
    PURPOSE VARCHAR2(50),
    REQUEST_STATE VARCHAR2(10),
    RECEIPT_FILENAME VARCHAR2(60));
    
    
CREATE SEQUENCE EMPLOYEE_ID_SEQUENCE
  MINVALUE 1000
  MAXVALUE 9999
  START WITH 1
  INCREMENT BY 1
  CACHE 10;
  
  CREATE SEQUENCE MANAGER_ID_SEQUENCE
  MINVALUE 10000
  START WITH 10000
  INCREMENT BY 3
  CACHE 10;
  
CREATE SEQUENCE REQUEST_ID_SEQUENCE
  MINVALUE 5000
  START WITH 5000
  INCREMENT BY 13
  CACHE 10;
COMMIT;

CREATE OR REPLACE TRIGGER TR_INSERT_EMPLOYEE_ID
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN 
SELECT EMPLOYEE_ID_SEQUENCE.NEXTVAL INTO :NEW.EMP_ID FROM DUAL;
END;
/
COMMIT;

CREATE OR REPLACE TRIGGER TR_INSERT_MANAGER_ID
BEFORE INSERT ON MANAGER
FOR EACH ROW
BEGIN 
SELECT MANAGER_ID_SEQUENCE.NEXTVAL INTO :NEW.MAN_ID FROM DUAL;
END;
/
COMMIT;

CREATE OR REPLACE TRIGGER TR_INSERT_EMPLOYEE_ID
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN 
SELECT EMPLOYEE_ID_SEQUENCE.NEXTVAL INTO :NEW.EMP_ID FROM DUAL;
END;
/
COMMIT;

INSERT INTO EMPLOYEE (EMP_ID, FIRSTNAME, LASTNAME, EMAIL, EMP_PASSWORD, ROUTING_NUMBER, ACCOUNT_NUMBER)
VALUES ('Jaden', 'Park', 'jpark@gmail.com', '123456', 148546, 6456665884);
INSERT INTO EMPLOYEE (EMP_ID, FIRSTNAME, LASTNAME, EMAIL, EMP_PASSWORD, ADDRESS, CITY, STATE, ROUTING_NUMBER, ACCOUNT_NUMBER)
VALUES ('Keala', 'Best', 'kbest@gmail.com', 'password', '3899 Bird Street', 'Penasco', 'New Mexico', 8756896, 46846843);
INSERT INTO EMPLOYEE (EMP_ID, FIRSTNAME, LASTNAME, EMAIL, EMP_PASSWORD, ADDRESS, CITY, STATE, ROUTING_NUMBER, ACCOUNT_NUMBER)
VALUES ('Sam', 'Fisher', 'sfisher@gmail.com', '456789', '3078 Red Bud Lane', 'New Haven', 'Connecticut', 56686415, 2686648);
INSERT INTO EMPLOYEE (EMP_ID, FIRSTNAME, LASTNAME, EMAIL, EMP_PASSWORD, ADDRESS, CITY, STATE, ROUTING_NUMBER, ACCOUNT_NUMBER)
VALUES ('Jennifer ', 'Kelly', 'deie2008@hotmail.com', 'psswrd', ' 419 Thompson Drive', 'Oakland', 'California', 56686415, 156548415);


INSERT INTO MANAGER (MAN_ID, FIRSTNAME, LASTNAME, EMAIL, EMP_PASSWORD, ROUTING_NUMBER, ACCOUNT_NUMBER)
VALUES ('Jaden', 'Park', 'jpark@gmail.com', '123456', 148546, 6456665884);
    
    
    