--CREATE TWO TABLES: EMPLOYEE
CREATE TABLE EMPLOYEE(EMPLOYEE_ID NUMBER, EMP_FIRSTNAME VARCHAR2,
						EMP_LASTNAME VARCHAR2, DEPARTMENT_ID NUMBER,
						SALARY NUMBER, EMP_EMAIL VARCHAR2
						CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID));
--CREATE TWO TABLES: DEPARTMENT
CREATE TABLE DEPARTMENT(DEPARTMENT_ID NUMBER, DEPARTMENT_NAME STRING
						CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DEPARTMENT_ID));

--SEQUENCE TO AUTO-GENERATE PRIMARY KEY VALUES FOR EMPLOYEE TABLE
CREATE SEQUENCE employee_seq
MINVALUE 1
MAXVALUE 1000
START WITH 1
INCREMENT BY 1
CACHE 100;

--SEQUENCE TO AUTO-GENERATE PRIMARY KEY VALUES FOR DEPARTMENT TABLE
CREATE SEQUENCE department_seq
MIN VALUE 1
MAXVALUE 50
START WITH 1
INCREMENT BY 1
CACHE 100;

--CREATE 6 NEW EMPLOYEES
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
				VALUES(employee_seq.NEXTVAL, John, Hopkins, 2, 50000, jhopkinds@cchallenge.com); 
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
				VALUES(employee_seq.NEXTVAL, Bill, Chore, 1, 60000, bchore@cchallenge.com); 
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
				VALUES(employee_seq.NEXTVAL, Rain, Wilson, 3, 45000, rwilson@cchallenge.com); 
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
				VALUES(employee_seq.NEXTVAL, Dwight, Schrute, 2, 65000, dschrute@cchallenge.com); 
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
				VALUES(employee_seq.NEXTVAL, Angie, Stone, 2, 60000, astone@cchallenge.com); 
INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
				VALUES(employee_seq.NEXTVAL, Shirley, Easton, 1, 71000, seaston@cchallenge.com); 
				
--CREATE 3 NEW DEPARTMENTS				
INSERT INTO DEPARTMENT(DEPARTMENT_ID, DEPARTMENT_NAME)
				VALUES(department_seq.NEXTVAL, 'IT');
INSERT INTO DEPARTMENT(DEPARTMENT_ID, DEPARTMENT_NAME)
				VALUES(department_seq.NEXTVAL, 'Sales');
INSERT INTO DEPARTMENT(DEPARTMENT_ID, DEPARTMENT_NAME)
				VALUES(department_seq.NEXTVAL, 'Manager');
		
--CREATE A STORED PROCEDURE TO TAKE IN DEPT_ID AND INCREASE EACH EMPLOYEE'S SALARY WITHIN THE 
--DEPARTMENT BY 10%		
CREATE OR REPLACE PROCEDURE SP_GIVE_RAISE (DEPT_ID NUMBER)
AS	
BEGIN

	SELECT DEPARTMENT_NAME, SALARY 
	FROM EMPLOYEE, DEPARTMENT
	AVG(SALARY)

END SP_GIVE_RAISE;

			