CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID int NOT NULL PRIMARY KEY,
    EMP_FIRSTNAME varchar(255),
    EMP_LASTNAME varchar(255),
    DEPARTMENT_ID varchar(255),
    SALARY float,
    EMP_EMAIL varchar(255)
);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_NAME varchar(255) NOT NULL PRIMARY KEY,
    FOREIGN KEY(DEPARTMENT_ID)  REFERENCES EMPLOYEE(EMPLOYEE_ID))
    ;

CREATE SEQUENCE INCREMENT_SEQUENCE
MINVALUE 1
START WITH 1
INCREMENT BY 1; 

CREATE OR REPLACE TRIGGER AUTO_INCREMENT 
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW
BEGIN 
SELECT INCREMENT_TRIGGER.NEXTVAL
INTO   :INCREMENTS
FROM   dual;
END;




INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES (1, 'Jim', 'Williams', 2, '5500', 'jim@email.com');

INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES (1, 'Rebecca', 'Jones', 2, '7500', 'rebecca@email.com');

INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES (1, 'Eric', 'Bill', 2, '9500', 'eric@email.com');

INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES (2, 'Nancy', 'Richards', 2, '10500', 'nancy@email.com');

INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES (2, 'Julia', 'Nina', 2, '12500', 'julia@email.com');

INSERT INTO EMPLOYEE(EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES (3, 'Matt', 'Hank', 2, '3500', 'matt@email.com');

INSERT INTO DEPARTMENT(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (1, 'Customer Service');

INSERT INTO DEPARTMENT(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (2, 'Sales');

INSERT INTO DEPARTMENT(DEPARTMENT_ID, DEPARTMENT_NAME)
VALUES (3, 'Cleaning');

CREATE OR REPLACE PROCEDURE SP_GIVE_RAISE
(DEP_ID IN DEPARTMENT_ID.DEPARTMENT%TYPE)
AS
BEGIN
SELECT AVG(SALARY + SALARY*.15) INTO AVERAGE_SALARY FROM EMPLOYEE WHERE DEP_ID = DEPARTMENT_ID;

END;
/





