server:
  port: 9090
  
spring:
  application:
    name: zuul
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  prefix: /api
  routes:
    test:
      path: /takeMeToBob/**
      url: http://bobrosslipsum.com/
    trex-by-address:
      path: /tba/**
      url: http://localhost:8988
    trex-by-service-name:
      path: /tbs/**
      serviceId : trex-service
     