
CREATE TABLE EMPLOYEE (
emp_id INT,
user_name VARCHAR2(50),
user_pass VARCHAR2(50),
first_name VARCHAR2(50),
last_name VARCHAR(50),
emp_email VARCHAR(100),
managing INT,
managed_by INT,
CONSTRAINT PK_EMPS PRIMARY KEY (emp_id)
);
CREATE TABLE REIBREQUEST (
req_id INT,
req_emp_id INT,
approving_emp_id INT,
receipt_id INT,
approved INT,
pending INT,
AMOUNT NUMBER,
DESCRIPTION VARCHAR2(1000),
FILENAME VARCHAR2s(300)
CONSTRAINT PK_REQUEST PRIMARY KEY (req_id)
);



ALTER TABLE EMPLOYEE ADD CONSTRAINT EMP_UNIQUE UNIQUE(user_name);
/
ALTER TABLE REIBREQUEST ADD AMOUNT NUMBER;
/
ALTER TABLE REIBREQUEST ADD CONSTRAINT FK_APR_EMP_ID 
FOREIGN KEY (approving_emp_id) REFERENCES EMPLOYEE (emp_id);
/
ALTER TABLE REIBREQUEST ADD CONSTRAINT FK_REQ_EMP_ID 
FOREIGN KEY (req_emp_id) REFERENCES EMPLOYEE (emp_id);
/
CREATE SEQUENCE emp_seq
MINVALUE 1000
START WITH 1000
INCREMENT BY 1;
/

CREATE SEQUENCE request_seq
MINVALUE 1000
START WITH 1000
INCREMENT BY 1;
/
CREATE OR REPLACE PROCEDURE SP_ADD_EMPLOYEE
(
EMP_USERNAME IN VARCHAR2,
EMP_PASSWORD IN VARCHAR2,
EMP_FNAME IN VARCHAR2,
EMP_LNAME IN VARCHAR2,
EMP_EMAIL IN VARCHAR2,
EMP_MANAGING IN INT,
EMP_MANAGED_BY IN INT
)
AS
BEGIN
INSERT INTO EMPLOYEE VALUES (EMP_SEQ.NEXTVAL,EMP_USERNAME,EMP_PASSWORD,EMP_FNAME,EMP_LNAME,EMP_EMAIL,EMP_MANAGING,EMP_MANAGED_BY);
END;
/

/
CREATE OR REPLACE PROCEDURE SP_ADD_REIB_REQUEST
(
EMPLOYEE_ID IN INT,
AMOUNT_REQ IN NUMBER,
RCPT IN BLOB
)
IS
REQ_EMP_ID INT;
MANAGER_ID INT;
BEGIN
SELECT EMP_ID INTO REQ_EMP_ID FROM EMPLOYEE WHERE EMP_ID = EMPLOYEE_ID;
SELECT MANAGED_BY INTO MANAGER_ID FROM EMPLOYEE WHERE EMP_ID=EMPLOYEE_ID;
INSERT INTO REIBREQUEST VALUES (request_seq.nextval,  REQ_EMP_ID,  MANAGER_ID, 0, 1,  RCPT,  AMOUNT_REQ);
END;
/

CREATE OR REPLACE PROCEDURE SP_DENY_REQUEST
(
REQUEST IN INT,
MGR_ID IN INT
)
AS
BEGIN
UPDATE REIBREQUEST SET APPROVED = 0, PENDING = 0 WHERE REQ_ID = REQUEST AND APPROVING_EMP_ID =MGR_ID;
END;
/
CREATE OR REPLACE PROCEDURE SP_APPROVE_REQUEST
(
REQUEST IN INT,
MGR_ID IN INT
)
AS
BEGIN
UPDATE REIBREQUEST SET APPROVED = 1, PENDING = 0 WHERE REQ_ID = REQUEST AND APPROVING_EMP_ID =MGR_ID;
END;
/
CREATE OR REPLACE PROCEDURE SP_SET_MANAGER 
(
EMPLOYEE_ID IN INT,
MGR_FIRST_NAME IN VARCHAR2,
MGR_LAST_NAME IN VARCHAR2)
IS
MGR_ID INT;
BEGIN 
SELECT EMP_ID INTO MGR_ID FROM EMPLOYEE WHERE FIRST_NAME=MGR_FIRST_NAME AND LAST_NAME=MGR_LAST_NAME AND MANAGING=1;
UPDATE EMPLOYEE SET MANAGED_BY = MGR_ID WHERE EMP_ID = EMPLOYEE_ID;
END;

/


SELECT * FROM REIBREQUEST;
UPDATE REIBREQUEST SET AMOUNT = 50;
COMMIT;
SELECT * FROM EMPLOYEE;
EXEC SP_DENY_REQUEST(1002,1022);
COMMIT;