DROP TABLE ACCOUNTS;
DROP TABLE CUSTOMER;
DROP TABLE SECURITY;


--CUSTOMER TABLE 
CREATE TABLE CUSTOMER (
    USERID NUMBER NOT NULL, 
    F_NAME VARCHAR2(200),
    L_NAME VARCHAR2(200), 
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (USERID),
    ACCOUNTNUMBER NUMBER(10,2)
    );
    
-- ACCOUNTS TABLE
CREATE TABLE ACCOUNTS(
    USERID NUMBER NOT NULL,
    ACCOUNTID NUMBER NOT NULL, 
    SAVINGS FLOAT(40),
    ACCOUNTNUMBER NUMBER(10,2),
    CONSTRAINT PK_ACCOUNTS PRIMARY KEY (ACCOUNTID),
    CONSTRAINT FK_CUSTOMER
        FOREIGN KEY(USERID)
        REFERENCES CUSTOMER(USERID)
        ON DELETE CASCADE
        
    );
-- SECURITY TABLE
CREATE TABLE SECURITY (
    USERID NUMBER NOT NULL,
    USERNAME VARCHAR2(200),
    PASSWORD_KEY VARCHAR2(200),
    CONSTRAINT FK_SECURITY
        FOREIGN KEY(USERID)
        REFERENCES CUSTOMER(USERID)
        ON DELETE CASCADE
    );
    
CREATE SEQUENCE CUSTOMER_ID_GEN 
START WITH 1001
INCREMENT BY 1;

CREATE SEQUENCE ACCOUNTS_ID_GEN 
START WITH 1001
INCREMENT BY 1;

CREATE OR REPLACE PROCEDURE CREATE_NEW_CUSTOMER(
FIRST_N IN VARCHAR2,LAST_N IN VARCHAR2,USERNAME_N IN VARCHAR2,PASSWORD_N IN VARCHAR2)
AS 
ACCOUNT_ID NUMBER;
CUSTOMER_ID NUMBER;
BEGIN 
    ACCOUNT_ID := ACCOUNTS_ID_GEN.NEXTVAL;
    CUSTOMER_ID := CUSTOMER_ID_GEN.NEXTVAL;
   
    -- CUSTOMER TABLE ADDITION
    INSERT INTO CUSTOMER(USERID,F_NAME,L_NAME,ACCOUNTNUMBER)
    VALUES(CUSTOMER_ID,FIRST_N,LAST_N,ACCOUNT_ID);
    
    -- ACCOUNTS TABLE ADDITION
    INSERT INTO ACCOUNTS(USERID,ACCOUNTID,ACCOUNTNUMBER)
    VALUES(CUSTOMER_ID,ACCOUNT_ID,CUSTOMER_ID);
    -- SECURITY TABLE ADDITION
    INSERT INTO SECURITY(USERID,USERNAME,PASSWORD_KEY)
    VALUES(CUSTOMER_ID,USERNAME_N,PASSWORD_N);
    
    
END;
/

CREATE OR REPLACE FUNCTION USERNAME_AVAILABILITY(USER_NAME IN VARCHAR)
RETURN SYS_REFCURSOR
AS
my_cursor SYS_REFCURSOR;
BEGIN
  OPEN my_cursor FOR SELECT * FROM SECURITY WHERE USER_NAME = USERNAME;
  RETURN my_cursor;
END;

CREATE OR REPLACE PROCEDURE DELETE_ACCOUNT (ACCOUNT_ID IN NUMBER)
AS 
ACCOUNT_NUMBER NUMBER;
BEGIN
    SELECT ACCOUNTNUMBER INTO ACCOUNT_NUMBER FROM ACCOUNTS WHERE ACCOUNTID = ACCOUNT_ID; 
    DELETE FROM CUSTOMER WHERE ACCOUNTNUMBER = ACCOUNT_NUMBER;   
        
END;
/


    



    
    