INSERT INTO EMPLOYEE_TITLE VALUES ('MANAGER');
INSERT INTO EMPLOYEE_TITLE VALUES ('EMPLOYEE');

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, USERNAME, PASSWORD, EMAIL, EMPL_TYPE)
VALUES('John', 'Smith', 'jsmith', 'password', 'jsmith@email.com', 'MANAGER');

INSERT INTO REQUEST_STATUS VALUES ('APPROVED');
INSERT INTO REQUEST_STATUS VALUES ('DENIED');

COMMIT;