INSERT INTO EMPLOYEE_TITLE VALUES ('MANAGER');
INSERT INTO EMPLOYEE_TITLE VALUES ('EMPLOYEE');

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, USERNAME, PASSWORD, EMAIL, EMPL_TYPE)
VALUES('John', 'Smith', 'jsmith', 'password', 'jsmith@email.com', 'MANAGER');

INSERT INTO REQUEST_STATUS VALUES ('APPROVED');
INSERT INTO REQUEST_STATUS VALUES ('DENIED');

INSERT INTO REIMBURSEMENT_REQUEST (AMOUNT, REQ_DATE, EMPL_ID, RECEIPT, DESCRIPTION) VALUES
(200, SYSDATE, 1044, NULL, 'PIZZA');
INSERT INTO REIMBURSEMENT_REQUEST (AMOUNT, REQ_DATE, EMPL_ID, RECEIPT, DESCRIPTION) VALUES
(400, SYSDATE, 1044, NULL, 'PARTY  TIME');
INSERT INTO PROCESSED_REQUESTS (REQ_ID, MANAGER_ID, PROCESSED_ON, STATUS) VALUES
(1001, 1021, SYSDATE, 'APPROVED');

SELECT * FROM REIMBURSEMENT_REQUEST WHERE EMPL_ID = 1044 AND REQ_ID NOT IN (SELECT REQ_ID FROM PROCESSED_REQUESTS);

COMMIT;