


CREATE TABLE EMPLOYEE_TYPE (
    TYPE_NAME VARCHAR(20) PRIMARY KEY
);

CREATE TABLE REQUEST_STATUS (
    STATUS_NAME VARCHAR(10)
);

CREATE TABLE EMPLOYEE (
    EMPL_ID INTEGER PRIMARY KEY,
    FIRSTNAME VARCHAR(30),
    LASTNAME  VARCHAR(30),
    USERNAME VARCHAR(20) UNIQUE,
    PASSWORD VARCHAR(20),
    EMPL_TYPE VARCHAR(20)
);

CREATE TABLE REIMBURSEMENT_REQUEST (
    REQ_ID INTEGER PRIMARY KEY,
    AMOUNT NUMBER,
    REQ_DATE DATE,
    EMPL_ID INTEGER,
    DESCRIPTION VARCHAR2(200)
);

CREATE TABLE  PROCESSED_REQUESTS (
    PR_ID INTEGER PRIMARY KEY,
    REQ_ID INTEGER,
    MANAGER_ID INTEGER,
    STATUS VARCHAR(10)
);