DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE REIMBURSEMENTS CASCADE CONSTRAINTS;

/***************************************************************************************
*                                   CREATE TABLES                                      *
****************************************************************************************/
CREATE TABLE USERS(
    USER_ID INTEGER NOT NULL,
    FIRST_NAME VARCHAR2(120) NOT NULL,
    LAST_NAME VARCHAR2(120) NOT NULL,
    USERNAME VARCHAR2(120) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(120) NOT NULL,
    EMAIL VARCHAR2(120) NOT NULL,
    POSITION INTEGER NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY(USER_ID)
);

CREATE TABLE POSITIONS(
    POSITION_ID INTEGER NOT NULL,
    POSITION_CODE VARCHAR(120),
    CONSTRAINT PK_POSITION PRIMARY KEY(POSITION_ID)
);

CREATE TABLE REIMBURSEMENTS(
    REIMBURSEMENT_ID INTEGER NOT NULL,
    AMOUNT NUMBER NOT NULL,
    STATUS INTEGER DEFAULT 1,
    FILE_TYPE BLOB,
    DATE_SUBMITTED TIMESTAMP,
    EMPLOYEE_ID NUMBER NOT NULL,
    MANAGER_ID NUMBER,
    CONSTRAINT PK_REIMBURSEMENT PRIMARY KEY(REIMBURSEMENT_ID),
    CONSTRAINT CHK_MANAGER CHECK(MANAGER_ID != EMPLOYEE_ID)
);

CREATE TABLE STATUS(
    STATUS_ID INTEGER,
    STATUS_CODE VARCHAR2(120) NOT NULL,
    CONSTRAINT PK_STATUS PRIMARY KEY (STATUS_ID)
);


/***************************************************************************************
*                                   FOREIGN KEYS                                       *
****************************************************************************************/

ALTER TABLE REIMBURSEMENTS ADD CONSTRAINT FK_EMPLOYEE_ID
    FOREIGN KEY(EMPLOYEE_ID) REFERENCES USERS(USER_ID);
    
ALTER TABLE REIMBURSEMENTS ADD CONSTRAINT FK_MANAGER_ID
    FOREIGN KEY(MANAGER_ID) REFERENCES USERS(USER_ID);
    
ALTER TABLE REIMBURSEMENTS ADD CONSTRAINT FK_STATUS
    FOREIGN KEY(STATUS) REFERENCES STATUS(STATUS_ID);

ALTER TABLE USERS ADD CONSTRAINT FK_POSITION
    FOREIGN KEY(POSITION) REFERENCES POSITIONS(POSITION_ID);
    

/***************************************************************************************
*                                  INSERTING VALUES                                    *
****************************************************************************************/

INSERT INTO STATUS VALUES(1, 'PENDING');
INSERT INTO STATUS VALUES(2, 'APPROVED');
INSERT INTO STATUS VALUES(3, 'DENIED');
    
INSERT INTO POSITIONS VALUES(1, 'EMPLOYEE');
INSERT INTO POSITIONS VALUES(2, 'MANAGER');

CREATE SEQUENCE USER_ID_SEQ START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE REIMBURSEMENT_ID_SEQ START WITH 1001 INCREMENT BY 1;

CREATE OR REPLACE PROCEDURE ADDREIMBURSEMENT(TYPE_OF_FILE BLOB, EMP_ID NUMBER) AS
BEGIN
    INSERT INTO REIMBURSEMENTS(REIMBURSEMENT_ID, FILE_TYPE, EMPLOYEE_ID, DATE_SUBMITTED) VALUES (REIMBURSEMENT_ID_SEQ.NEXTVAL, TYPE_OF_FILE, EMP_ID, SYSTIMESTAMP);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE ADDMANAGER (F_NAME VARCHAR2, L_NAME VARCHAR2, U_NAME VARCHAR2, PASS VARCHAR2, MAIL VARCHAR2) AS
BEGIN
    INSERT INTO USERS VALUES(USER_ID_SEQ.NEXTVAL, F_NAME, L_NAME, U_NAME, PASS, MAIL, 2);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE ADDEMPLOYEE (F_NAME VARCHAR2, L_NAME VARCHAR2, U_NAME VARCHAR2, PASS VARCHAR2, MAIL VARCHAR2) AS
BEGIN
    INSERT INTO USERS VALUES(USER_ID_SEQ.NEXTVAL, F_NAME, L_NAME, U_NAME, PASS, MAIL, 1);
COMMIT;
END;
/

EXECUTE ADDMANAGER('Conan', 'Chan', 'cchan16', 'password', 'chanconan67@gmail.com');
EXECUTE ADDEMPLOYEE('Jon', 'Snow', 'jsnow', 'jsnowpassword', 'youknownothing@gmail.com');
EXECUTE ADDMANAGER('Nathan', 'Bandong', 'guazm', 'password', 'itsguazm@gmail.com');
EXECUTE ADDEMPLOYEE('Wilson', 'Yan', 'yanman23', 'password', 'yanman23@gmail.com');
EXECUTE ADDEMPLOYEE('Allison', 'Hyatt', 'ahyatt', 'password', 'ahyatt@gmail.com');

INSERT INTO REIMBURSEMENTS(REIMBURSEMENT_ID, EMPLOYEE_ID, DATE_SUBMITTED, STATUS, AMOUNT) VALUES (REIMBURSEMENT_ID_SEQ.NEXTVAL, 1023, SYSDATE, 1, 100000000);

UPDATE REIMBURSEMENTS SET MANAGER_ID = 1003 AND STATUS = 2 WHERE REIMBURSEMENT_ID = 1006;
UPDATE STATUS SET STATUS_CODE = 'DECLINED' WHERE STATUS_ID = 3;
COMMIT;