--DROP TABLE ACCOUNTS;
--DROP TABLE USERS;
--DROP TABLE ROLES;
--DROP SEQUENCE SEQ_USERID;
--DROP SEQUENCE SEQ_ROLEID;
--DROP SEQUENCE SEQ_ACCOUNTID;

CREATE TABLE USERS (USERID NUMBER, ROLEID NUMBER, USERNAME VARCHAR2(30), PASSWORD VARCHAR2(50), LOGGED NUMBER(1), CONSTRAINT USERID_PK PRIMARY KEY(USERID));
CREATE TABLE ROLES(ROLEID NUMBER, ROLE VARCHAR2(20), CONSTRAINT ROLEID_PK PRIMARY KEY(ROLEID));
CREATE TABLE ACCOUNTS(ACCOUNTID NUMBER, ACCOUNTTYPE VARCHAR2(30), USERID NUMBER, BALANCE NUMBER(*,2), CONSTRAINT ACCOUNTID_PK PRIMARY KEY(ACCOUNTID));

-- Add constraints for foreign keys
-- ON DELETE CASCADE
ALTER TABLE USERS
ADD CONSTRAINT FK_CACADE_ROLEID FOREIGN KEY (ROLEID)
REFERENCES ROLES (ROLEID)
ON DELETE CASCADE;

ALTER TABLE ACCOUNTS
ADD CONSTRAINT FK_CASCADE_USERID FOREIGN KEY (USERID)
REFERENCES USERS (USERID)
ON DELETE CASCADE;

-- Add default value for logged
ALTER TABLE USERS
MODIFY (LOGGED DEFAULT 0);


CREATE SEQUENCE SEQ_USERID increment by 1;
CREATE SEQUENCE SEQ_ROLEID increment by 1;
CREATE SEQUENCE SEQ_ACCOUNTID increment by 1;

INSERT INTO USERS(userid, username, password, logged)
VALUES(SEQ_USERID.nextval,'','',0);

INSERT INTO ROLES(roleid, role)
VALUES(SEQ_ROLEID.nextval, '');

INSERT INTO ACCOUNTS(accountid, accounttype, userid, balance)
VALUES(SEQ_ACCOUNTID.nextval, '','',0);