CREATE TABLE CUSTOMER (
    USER_ID NUMBER NOT NULL,
    USER_NAME VARCHAR2(20),
    USER_PASS VARCHAR2(20),
    BANK_ACCOUNT_ID NUMBER NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (USER_ID)
);

CREATE TABLE BANKACCOUNT (
    BANK_ACCOUNT_ID NUMBER NOT NULL,
    BALANCE NUMBER NOT NULL,
    CONSTRAINT PK_BANKACCOUNT PRIMARY KEY (BANK_ACCOUNT_ID)
);

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_BANKACCOUNT
FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES BANKACCOUNT(BANK_ACCOUNT_ID);

CREATE SEQUENCE CUSTOMER_SEQ
    MINVALUE 1
    MAXVALUE 999
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE SEQUENCE ACCOUNT_SEQ
    MINVALUE 11
    MAXVALUE 999
    START WITH 11
    INCREMENT BY 1
    NOCACHE;

--DROP SEQUENCE CUSTOMER_SEQ;
--DROP SEQUENCE ACCOUNT_SEQ;
--DROP TRIGGER Before_Trig_IncUserId;
--DROP TRIGGER Before_Trig_IncAccountId;

CREATE OR REPLACE TRIGGER Before_Trig_IncUserId
BEFORE INSERT ON CUSTOMER
FOR EACH ROW
BEGIN
    SELECT CUSTOMER_SEQ.NEXTVAL
    INTO :NEW.USER_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER Before_Trig_IncAccountId
BEFORE INSERT ON BANKACCOUNT
FOR EACH ROW
BEGIN
    SELECT ACCOUNT_SEQ.NEXTVAL
    INTO :NEW.BANK_ACCOUNT_ID FROM DUAL;
END;
/

INSERT INTO BANKACCOUNT (BALANCE) VALUES (500);

INSERT INTO CUSTOMER  (USER_NAME, USER_PASS, BANK_ACCOUNT_ID) VALUES ('Jonny', 'Five', 14);
INSERT INTO CUSTOMER  (USER_NAME, USER_PASS, BANK_ACCOUNT_ID) VALUES ('Hello', 'Venus', 12);

SELECT * FROM BANKACCOUNT;
SELECT * FROM CUSTOMER;
