/*James Whitten
JDBC Bank Assignment
Due:2-5-18
*/


CREATE TABLE USERS
(
    USER_ID NUMBER NOT NULL,
    USER_ACCNAME VARCHAR2(60) NOT NULL,
    USER_FNAME VARCHAR2(60) NOT NULL,
    USER_LNAME VARCHAR2(60) NOT NULL,
    USER_PASSWORD VARCHAR2(60) NOT NULL,
    USER_TYPE NUMBER NOT NULL,
    CONSTRAINT PK_USER_ID PRIMARY KEY  (USER_ID)
);

CREATE TABLE ACCOUNTS
(
    BANK_ACCOUNT_ID NUMBER NOT NULL,
    BANK_ACCOUNT_TYPE NUMBER NOT NULL,
    CURRENCY_AMOUNT NUMBER NOT NULL,
    CONSTRAINT PK_BANK_ACCOUNT_ID PRIMARY KEY (BANK_ACCOUNT_ID)
);

CREATE TABLE TRANSACTIONS
(
    TRANS_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    TRANS_TIME TIMESTAMP NOT NULL,
    TRANS_AMOUNT NUMBER NOT NULL,
    BANK_ACCOUNT_ID NUMBER NOT NULL,
    TRANS_TYPE NUMBER NOT NULL,
    CONSTRAINT PK_TRANS_ID PRIMARY KEY (TRANS_ID)
);

CREATE TABLE USER_ACCOUNTS
(
    USER_ID NUMBER NOT NULL,
    BANK_ACCOUNT_ID NUMBER NOT NULL,
    CONSTRAINT PK_USER_ACCOUNTS_ID PRIMARY KEY (USER_ID, BANK_ACCOUNT_ID)
);

CREATE TABLE TYPE_LOOKUPS
(
    TYPE_ID NUMBER NOT NULL,
    LOOKUP_TYPE VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_TYPE_LOOKUPS PRIMARY KEY (TYPE_ID)
);
    

ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRANS_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ;

ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRANS_ACCOUNT
    FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES ACCOUNTS (BANK_ACCOUNT_ID) ;
    
ALTER TABLE USER_ACCOUNTS ADD CONSTRAINT FK_ACCOUNT_USER
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ; 
    
ALTER TABLE USER_ACCOUNTS ADD CONSTRAINT FK_USER_ACCOUNTS
    FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES ACCOUNTS (BANK_ACCOUNT_ID);
    
ALTER TABLE USERS ADD CONSTRAINT FK_USER_TYPE
    FOREIGN KEY (USER_TYPE) REFERENCES TYPE_LOOKUPS (TYPE_ID);
    
ALTER TABLE ACCOUNTS ADD CONSTRAINT FK_ACCOUNT_TYPE
    FOREIGN KEY (BANK_ACCOUNT_TYPE) REFERENCES TYPE_LOOKUPS (TYPE_ID);
    
ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRANS_TYPE
    FOREIGN KEY (TRANS_TYPE) REFERENCES TYPE_LOOKUPS (TYPE_ID);
  
ALTER TABLE USERS ADD CONSTRAINT U_ACCOUNTNAME UNIQUE (USER_ACCNAME);

CREATE SEQUENCE USER_NUM_SEQ
START WITH 1001;

CREATE SEQUENCE ACC_NUM_SEQ
START WITH 11;

CREATE SEQUENCE TRANS_NUM_SEQ;

SELECT USER_NUM_SEQ.NEXTVAL FROM DUAL;
SELECT USER_NUM_SEQ.CURRVAL FROM DUAL;

INSERT INTO TYPE_LOOKUPS (TYPE_ID, LOOKUP_TYPE)
VALUES (1, 'Super User');    

INSERT INTO TYPE_LOOKUPS (TYPE_ID, LOOKUP_TYPE)
VALUES (2, 'User');

INSERT INTO TYPE_LOOKUPS (TYPE_ID, LOOKUP_TYPE)
VALUES (3, 'Checking');

INSERT INTO TYPE_LOOKUPS (TYPE_ID, LOOKUP_TYPE)
VALUES (4, 'Savings');

INSERT INTO USERS (USER_ID, USER_ACCNAME, USER_FNAME, USER_LNAME, USER_PASSWORD, USER_TYPE)
VALUES(USER_NUM_SEQ.NEXTVAL,'bobdole','Bob','Dole','44bottlesofbeeronthewall',1);

CREATE OR REPLACE FUNCTION ACCS_FOR_USER(U_ID NUMBER) RETURN NUMBER IS
USE_ACCOUNTS NUMBER;
BEGIN
SELECT COUNT(USER_ID) INTO USE_ACCOUNTS
FROM USER_ACCOUNTS
WHERE USER_ID = U_ID;
RETURN USE_ACCOUNTS;
END ACCS_FOR_USER;
/

CREATE OR REPLACE PROCEDURE DEL_ALL_USERS IS
BEGIN
UPDATE USERS
SET USER_PASSWORD = 'DEL'
WHERE USER_TYPE = 2;
END DEL_ALL_USERS;
/
