CREATE TABLE EMPLOYEE(
  EMPLOYEE_ID INT PRIMARY KEY,
  EMP_FIRSTNAME VARCHAR2(40),
  EMP_LASTNAME VARCHAR2(40),
  DEPARTMENT_ID INT,
  SALARY NUMBER,
  EMP_EMAIL VARCHAR2(40),
  );
  
CREATE TABLE DEPARTMENT(
  DEPARTMENT_ID INT PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR2(40),
  );
  
--ALTER TABLE EMPLOYEE
--ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT
--FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID);

CREATE OR REPLACE SEQUENCE EMPLOYEE_ID_SEQ
MINVALUE 1001;

CREATE OR REPLACE SEQUENCE DEPARTMENT_ID_SEQ
MINVALUE 1001;

CREATE TRIGGER EMPLOYEE_PK
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
SELECT EMPLOYEE_ID_SEQ.NEXTVAL INTO:NEW.C_ID FROM DUAL;
END;

CREATE TRIGGER DEPARTMENT_PK
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
SELECT DEPARTMENT_ID_SEQ.NEXTVAL INTO:NEW.C_ID FROM DUAL;
END;

INSERT INTO EMPLOYEE VALUES('Jeff','Bridges',100,000,'JeffBridges@msn.com');
INSERT INTO EMPLOYEE VALUES('Nancy','Sally',120,000,'NanySally@msn.com');
INSERT INTO EMPLOYEE VALUES('Dan','Anderson',67,000,'DanAnderson@msn.com');
INSERT INTO EMPLOYEE VALUES('Suzie','Derkins',82,000,'SuzieDerkins@msn.com');
INSERT INTO EMPLOYEE VALUES('Laura','Smith',44,000,'LauraSmith@msn.com'); 
INSERT INTO EMPLOYEE VALUES('Jim','Miller',32,000,'JimMiller@msn.com');

INSERT INTO DEPARMENT VALUES('Sales');
INSERT INTO DEPARTMENT VALUES('Human Resources');
INSERT INTO DEPARTMENT VALUES('Advertising');

CREATE OR REPLACE PROCEDURE SP_GIVE_RAISE(D_ID IN INT, NEW_AVG_SALARY OUT NUMBER, VALID_DEPARTMENT OUT BOOLEAN)
  AS
  BEGIN 
  SELECT E.SALARY * 1.1, SUM(E.SALARY * 1.1)
  INTO E.SALARY, NEW_AVG_SALARY
  FROM EMPLOYEE E 
  WHERE E.DEPARTMENT_ID = D_ID;
  VALID_DEPARTMENT = (D_ID IN EMPLOYEE);
  RETURN NEW_AVG_SALARY
  END;
  /